###############################
# USERS & GROUPS
###############################
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: tanzu
  description: The VMware Tanzu Organization
  links:
    - url: http://tanzu.vmware.com/
      title: Website
spec: 
  type: organization
  profile:
    displayName: Tanzu
    email: tanzu@vmware.com
    picture: https://pbs.twimg.com/profile_images/1233138813939146752/YPCsKoIa_400x400.png
  children: []
  
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ben.wilcock
  description: Ben is an innovator - constantly looking for ways to improve developer productivity.
  links:
    - url: https://www.linkedin.com/in/benwilcock/
      title: Ben Wilcock On LinkedIn (Follow).
      type: website
      icon: WebAsset
    - url: https://www.youtube.com/@BenWilcock
      title: Ben Wilcock On YouTube
      type: website
      icon: WebAsset
spec:
  memberOf: [tanzu]
  profile:
    displayName: Ben Wilcock
    picture: https://pbs.twimg.com/profile_images/1577303225677615107/f0lW_xGN_400x400.jpg

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: openai
  description: The creators of ChatGPT
spec:
  type: company
  children: []
  profile:
    displayName: OpenAI
    email: info@openai.com
    picture: https://yt3.googleusercontent.com/UqT_vCkJIn1P2fH1pchr6lbe3xeEekY61h4bUpJkVuityqKOEtUYcNy3pLiJ5OKdj4uKA81FWE8=s176-c-k-c0x00ffffff-no-rj

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: open-source
  description: The creators of ChatGPT
spec:
  type: movement
  children: []
  profile:
    displayName: Open Source


###############################
# SYSTEMS
###############################
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backchat
  description: "Bringing Generative AI into Backstage."
  tags:
    - backstage
    - backchat
  links:
    - url: https://www.npmjs.com/package/@benbravo73/backstage-plugin-backchat
      title: Backchat Plugin Page On NPM
      type: website
      icon: WebAsset
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/benwilcock/backstagecon-2023/blob/main/
spec: 
  owner: user:ben.wilcock
  profile:
    displayName: Backchat
    picture: https://raw.githubusercontent.com/benwilcock/backstagecon-2023/main/text-generation-webui-config/characters/Backchat.png



####################################
# COMPONENTS
####################################
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backchat-plugin
  description: 'This plugin integrates Private AI GUIs into Backstage'
  links:
    - url: https://github.com/benwilcock/backstage-plugin-backchat
      title:  Website
      type: website
      icon: WebAsset
  tags:
    - backchat
spec:
  type: service
  lifecycle: production
  owner: user:ben.wilcock
  system: backchat
  profile:
    displayName: Backchat Plugin
    picture: https://raw.githubusercontent.com/benwilcock/backstagecon-2023/main/text-generation-webui-config/characters/Backchat.png
  dependsOn:
    - component:text-generation-web-ui
    - component:chatbot-ui
    - component:ollama-web-ui

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: localai
  description: 'LocalAI provides a ChatGPT compatible backend for private AI using popular LLMs'
  links:
    - url: https://localai.io
      title: Website
      type: website
      icon: WebAsset
    - url: http://localhost:8080/v1/models
      title: API Endpoint
      type: website
      icon: WebAsset
  tags:
    - backchat
    - localai
spec:
  type: service
  lifecycle: production
  system: backchat
  providesApis:
    - openai-api
  owner: group:open-source
  profile:
    displayName: LocalAI
  dependsOn:
    - resource:openllama-7b-open-instruct

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: text-generation-web-ui
  description: 'Text Generation Web UI provides a browser based GUI and a ChatGPT compatible backend for private AI using popular LLMs'
  links:
    - url: https://github.com/oobabooga/text-generation-webui
      title: Website
      type: website
      icon: WebAsset
    - url: http://localhost:7860
      title: GUI
      type: website
      icon: WebAsset
    - url: http://localhost:5001/v1/models
      title: API Endpoint
      type: website
      icon: WebAsset
  tags:
    - backchat
    - text-generation-web-ui
spec:
  type: service
  lifecycle: production
  system: backchat
  providesApis:
    - openai-api
  owner: group:open-source
  profile:
    displayName: Text Generation Web UI
  dependsOn:
    - resource:mistral-7b

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chatbot-ui
  description: 'Chatbot UI provides a browser based GUI compatible with backends offering the OpenAI API'
  links:
    - url: https://github.com/mckaywrigley/chatbot-ui
      title: Website
      type: website
      icon: WebAsset
    - url: http://localhost:8080
      title: GUI
      type: website
      icon: WebAsset
  tags:
    - backchat
    - chatbotui
spec:
  type: service
  lifecycle: production
  owner: group:open-source
  system: backchat
  profile:
    displayName: Text Generation Web UI
  dependsOn:
    - component:localai
    - component:text-generation-web-ui

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ollama-web-ui
  description: 'Ollama Web UI provides a browser based GUI for popular local LLMs'
  links:
    - url: https://github.com/ollama-webui/ollama-webui
      title: Website
      type: website
      icon: WebAsset
    - url: http://localhost:3100
      title: GUI
      type: website
      icon: WebAsset
  tags:
    - backchat
    - ollama-web-ui
spec:
  type: service
  lifecycle: production
  system: backchat
  owner: group:open-source
  profile:
    displayName: Ollama Web UI
  dependsOn:
    - component:ollama
    
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ollama
  description: 'Ollama provides a backend for the Ollama Web UI'
  links:
    - url: https://github.com/jmorganca/ollama
      title: Website
      type: website
      icon: WebAsset
    - url: http://localhost:11434/api/tags
      title: API Endpoint for listing models
      type: website
      icon: WebAsset
  tags:
    - backchat
    - ollama
spec:
  type: service
  lifecycle: production
  system: backchat
  owner: group:open-source
  profile:
    displayName: Ollama
  dependsOn:
    - resource:mistral-7b

####################################
# RESOURCES
####################################
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mistral-7b
  description: 'Mistral 7B, the most powerful language model for its size to date.'
  links:
    - url: https://mistral.ai/
      title: Mistral Website
      type: website
      icon: WebAsset
  tags:
    - large-language-model
spec:
  type: service
  lifecycle: production
  owner: user:ben.wilcock
  system: backchat
  profile:
    displayName: Mistral-7B

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: openllama-7b-open-instruct
  description: 'Instruction-tuned version of the fully trained Open LLama 7B model.'
  links:
    - url: https://huggingface.co/VMware/open-llama-7b-open-instruct
      title: VMware Page On Hugging Face
      type: website
      icon: WebAsset
  tags:
    - large-language-model
spec:
  type: service
  lifecycle: production
  owner: user:ben.wilcock
  system: backchat
  profile:
    displayName: "Openllama 7B Open Instruct"

######################################
# APIs
######################################
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: openai-api
  description: 'The API exposed by ChatGPT and compatible systems'
  tags:
    - api
    - openai-api
  links:
    - url: https://platform.openai.com/docs/api-reference
      title: OpenAI API Documentation
      type: website
      icon: WebAsset
spec:
  type: openapi
  lifecycle: production
  # system: backchat
  owner: group:openai
  definition:
    $text: https://github.com/benwilcock/backstagecon-2023/blob/main/openai-api-spec/openapi.yaml
