####################################
# COMPONENTS
####################################
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: chatbot-ui
  description: 'Chatbot UI provides a browser based GUI compatible with backends offering the OpenAI API'
  links:
    - url: https://github.com/gpustack/gpustack
      title: Website
      type: website
      icon: WebAsset
    - url: http://localhost:8090
      title: GUI
      type: website
      icon: WebAsset
  tags:
    - backchat
    - chatbotui
    - gpustack
spec:
  type: service
  lifecycle: production
  owner: group:open-source
  system: backchat
  profile:
    displayName: Text Generation Web UI
  dependsOn:
    - component:localai
    - component:text-generation-web-ui

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ollama
  description: 'Ollama provides a backend for the Ollama Web UI'
  links:
    - url: https://github.com/jmorganca/ollama
      title: Website
      type: website
      icon: WebAsset
    - url: http://localhost:11434/api/tags
      title: API Endpoint for listing models
      type: website
      icon: WebAsset
  tags:
    - backchat
    - ollama
spec:
  type: service
  lifecycle: production
  system: backchat
  owner: group:open-source
  profile:
    displayName: Ollama
  dependsOn:
    - resource:mistral-7b
